/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as AppApprovalsRouteImport } from './routes/app/approvals'
import { Route as AppAssistantRouteImport } from './routes/app/assistant'
import { Route as AppClinicalRouteImport } from './routes/app/clinical'
import { Route as AppComplianceRouteImport } from './routes/app/compliance'
import { Route as AppCustomerRouteImport } from './routes/app/customer'
import { Route as AppDocsRouteImport } from './routes/app/docs'
import { Route as AppFinanceRouteImport } from './routes/app/finance'
import { Route as AppGrantRouteImport } from './routes/app/grant'
import { Route as AppInvestorRouteImport } from './routes/app/investor'
import { Route as AppManufacturingRouteImport } from './routes/app/manufacturing'
import { Route as AppMarketingRouteImport } from './routes/app/marketing'
import { Route as AppMeetingsRouteImport } from './routes/app/meetings'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppPatentRouteImport } from './routes/app/patent'
import { Route as AppPeopleRouteImport } from './routes/app/people'
import { Route as AppProcurementRouteImport } from './routes/app/procurement'
import { Route as AppProjectsRouteImport } from './routes/app/projects'
import { Route as AppQualityRouteImport } from './routes/app/quality'
import { Route as AppRegulatoryRouteImport } from './routes/app/regulatory'
import { Route as AppResearchRouteImport } from './routes/app/research'
import { Route as AppSalesRouteImport } from './routes/app/sales'
import { Route as AppSupplyChainRouteImport } from './routes/app/supply-chain'
import { Route as AppTenderRouteImport } from './routes/app/tender'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppClinicalRoute = AppClinicalRouteImport.update({
  id: '/clinical',
  path: '/clinical',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomerRoute = AppCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppGrantRoute = AppGrantRouteImport.update({
  id: '/grant',
  path: '/grant',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorRoute = AppInvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => AppRoute,
} as any)
const AppManufacturingRoute = AppManufacturingRouteImport.update({
  id: '/manufacturing',
  path: '/manufacturing',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPatentRoute = AppPatentRouteImport.update({
  id: '/patent',
  path: '/patent',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppProcurementRoute = AppProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityRoute = AppQualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => AppRoute,
} as any)
const AppRegulatoryRoute = AppRegulatoryRouteImport.update({
  id: '/regulatory',
  path: '/regulatory',
  getParentRoute: () => AppRoute,
} as any)
const AppResearchRoute = AppResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppSupplyChainRoute = AppSupplyChainRouteImport.update({
  id: '/supply-chain',
  path: '/supply-chain',
  getParentRoute: () => AppRoute,
} as any)
const AppTenderRoute = AppTenderRouteImport.update({
  id: '/tender',
  path: '/tender',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/clinical': typeof AppClinicalRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/customer': typeof AppCustomerRoute
  '/app/docs': typeof AppDocsRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/grant': typeof AppGrantRoute
  '/app/investor': typeof AppInvestorRoute
  '/app/manufacturing': typeof AppManufacturingRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/patent': typeof AppPatentRoute
  '/app/people': typeof AppPeopleRoute
  '/app/procurement': typeof AppProcurementRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/quality': typeof AppQualityRoute
  '/app/regulatory': typeof AppRegulatoryRoute
  '/app/research': typeof AppResearchRoute
  '/app/sales': typeof AppSalesRoute
  '/app/supply-chain': typeof AppSupplyChainRoute
  '/app/tender': typeof AppTenderRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/clinical': typeof AppClinicalRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/customer': typeof AppCustomerRoute
  '/app/docs': typeof AppDocsRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/grant': typeof AppGrantRoute
  '/app/investor': typeof AppInvestorRoute
  '/app/manufacturing': typeof AppManufacturingRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/patent': typeof AppPatentRoute
  '/app/people': typeof AppPeopleRoute
  '/app/procurement': typeof AppProcurementRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/quality': typeof AppQualityRoute
  '/app/regulatory': typeof AppRegulatoryRoute
  '/app/research': typeof AppResearchRoute
  '/app/sales': typeof AppSalesRoute
  '/app/supply-chain': typeof AppSupplyChainRoute
  '/app/tender': typeof AppTenderRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/clinical': typeof AppClinicalRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/customer': typeof AppCustomerRoute
  '/app/docs': typeof AppDocsRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/grant': typeof AppGrantRoute
  '/app/investor': typeof AppInvestorRoute
  '/app/manufacturing': typeof AppManufacturingRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/patent': typeof AppPatentRoute
  '/app/people': typeof AppPeopleRoute
  '/app/procurement': typeof AppProcurementRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/quality': typeof AppQualityRoute
  '/app/regulatory': typeof AppRegulatoryRoute
  '/app/research': typeof AppResearchRoute
  '/app/sales': typeof AppSalesRoute
  '/app/supply-chain': typeof AppSupplyChainRoute
  '/app/tender': typeof AppTenderRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/sitemap.xml'
    | '/app/analytics'
    | '/app/approvals'
    | '/app/assistant'
    | '/app/clinical'
    | '/app/compliance'
    | '/app/customer'
    | '/app/docs'
    | '/app/finance'
    | '/app/grant'
    | '/app/investor'
    | '/app/manufacturing'
    | '/app/marketing'
    | '/app/meetings'
    | '/app/notifications'
    | '/app/patent'
    | '/app/people'
    | '/app/procurement'
    | '/app/projects'
    | '/app/quality'
    | '/app/regulatory'
    | '/app/research'
    | '/app/sales'
    | '/app/supply-chain'
    | '/app/tender'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/app/analytics'
    | '/app/approvals'
    | '/app/assistant'
    | '/app/clinical'
    | '/app/compliance'
    | '/app/customer'
    | '/app/docs'
    | '/app/finance'
    | '/app/grant'
    | '/app/investor'
    | '/app/manufacturing'
    | '/app/marketing'
    | '/app/meetings'
    | '/app/notifications'
    | '/app/patent'
    | '/app/people'
    | '/app/procurement'
    | '/app/projects'
    | '/app/quality'
    | '/app/regulatory'
    | '/app/research'
    | '/app/sales'
    | '/app/supply-chain'
    | '/app/tender'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/sitemap.xml'
    | '/app/analytics'
    | '/app/approvals'
    | '/app/assistant'
    | '/app/clinical'
    | '/app/compliance'
    | '/app/customer'
    | '/app/docs'
    | '/app/finance'
    | '/app/grant'
    | '/app/investor'
    | '/app/manufacturing'
    | '/app/marketing'
    | '/app/meetings'
    | '/app/notifications'
    | '/app/patent'
    | '/app/people'
    | '/app/procurement'
    | '/app/projects'
    | '/app/quality'
    | '/app/regulatory'
    | '/app/research'
    | '/app/sales'
    | '/app/supply-chain'
    | '/app/tender'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals': {
      id: '/app/approvals'
      path: '/approvals'
      fullPath: '/app/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clinical': {
      id: '/app/clinical'
      path: '/clinical'
      fullPath: '/app/clinical'
      preLoaderRoute: typeof AppClinicalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance': {
      id: '/app/compliance'
      path: '/compliance'
      fullPath: '/app/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customer': {
      id: '/app/customer'
      path: '/customer'
      fullPath: '/app/customer'
      preLoaderRoute: typeof AppCustomerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/docs': {
      id: '/app/docs'
      path: '/docs'
      fullPath: '/app/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/grant': {
      id: '/app/grant'
      path: '/grant'
      fullPath: '/app/grant'
      preLoaderRoute: typeof AppGrantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investor': {
      id: '/app/investor'
      path: '/investor'
      fullPath: '/app/investor'
      preLoaderRoute: typeof AppInvestorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/manufacturing': {
      id: '/app/manufacturing'
      path: '/manufacturing'
      fullPath: '/app/manufacturing'
      preLoaderRoute: typeof AppManufacturingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketing': {
      id: '/app/marketing'
      path: '/marketing'
      fullPath: '/app/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meetings': {
      id: '/app/meetings'
      path: '/meetings'
      fullPath: '/app/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/patent': {
      id: '/app/patent'
      path: '/patent'
      fullPath: '/app/patent'
      preLoaderRoute: typeof AppPatentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/people': {
      id: '/app/people'
      path: '/people'
      fullPath: '/app/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/procurement': {
      id: '/app/procurement'
      path: '/procurement'
      fullPath: '/app/procurement'
      preLoaderRoute: typeof AppProcurementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quality': {
      id: '/app/quality'
      path: '/quality'
      fullPath: '/app/quality'
      preLoaderRoute: typeof AppQualityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/regulatory': {
      id: '/app/regulatory'
      path: '/regulatory'
      fullPath: '/app/regulatory'
      preLoaderRoute: typeof AppRegulatoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/research': {
      id: '/app/research'
      path: '/research'
      fullPath: '/app/research'
      preLoaderRoute: typeof AppResearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales': {
      id: '/app/sales'
      path: '/sales'
      fullPath: '/app/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/supply-chain': {
      id: '/app/supply-chain'
      path: '/supply-chain'
      fullPath: '/app/supply-chain'
      preLoaderRoute: typeof AppSupplyChainRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tender': {
      id: '/app/tender'
      path: '/tender'
      fullPath: '/app/tender'
      preLoaderRoute: typeof AppTenderRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppClinicalRoute: typeof AppClinicalRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppCustomerRoute: typeof AppCustomerRoute
  AppDocsRoute: typeof AppDocsRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppGrantRoute: typeof AppGrantRoute
  AppInvestorRoute: typeof AppInvestorRoute
  AppManufacturingRoute: typeof AppManufacturingRoute
  AppMarketingRoute: typeof AppMarketingRoute
  AppMeetingsRoute: typeof AppMeetingsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPatentRoute: typeof AppPatentRoute
  AppPeopleRoute: typeof AppPeopleRoute
  AppProcurementRoute: typeof AppProcurementRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppQualityRoute: typeof AppQualityRoute
  AppRegulatoryRoute: typeof AppRegulatoryRoute
  AppResearchRoute: typeof AppResearchRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSupplyChainRoute: typeof AppSupplyChainRoute
  AppTenderRoute: typeof AppTenderRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppClinicalRoute: AppClinicalRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppCustomerRoute: AppCustomerRoute,
  AppDocsRoute: AppDocsRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppGrantRoute: AppGrantRoute,
  AppInvestorRoute: AppInvestorRoute,
  AppManufacturingRoute: AppManufacturingRoute,
  AppMarketingRoute: AppMarketingRoute,
  AppMeetingsRoute: AppMeetingsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPatentRoute: AppPatentRoute,
  AppPeopleRoute: AppPeopleRoute,
  AppProcurementRoute: AppProcurementRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppQualityRoute: AppQualityRoute,
  AppRegulatoryRoute: AppRegulatoryRoute,
  AppResearchRoute: AppResearchRoute,
  AppSalesRoute: AppSalesRoute,
  AppSupplyChainRoute: AppSupplyChainRoute,
  AppTenderRoute: AppTenderRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
